### ISSUE TITLE
Update to use mkdocstrings-python v1.8+

### ISSUE THREAD

**Issue by llucax** [analog-garage/mkdocstrings-python-xref#15]
`mkdocstrings-python` had a [few new releases](https://github.com/mkdocstrings/python/releases) with very interesting features that would be good to have available in this extension too.

I guess it is probably not doable, but it would be good if this extension could be somehow installed alongside any version of `mkdocstring-python`, so it is not necessary to catch up to every `mkdocstring-python`.

**Comment by analog-cbarber** [comment]
This extension actually depends on `mkdocstrings-python` and extends it by subclassing. The current dependency will work with any version of `mkdocstrings-python` from 1.6.2 to anything less than 2.0, so what you want should already be supported.

Did you actually try this and it didn't work?

**Comment by llucax** [comment]
Wooops. No, I think I just got fooled by the project version number and the version number in the `pyproject.toml` and I missed the `>=` relation. I just tried it and it works. Sorry for the noise!

I'm having one issue but it is totally unrelated to this, so I will open a different issue.
